import { NextResponse } from 'next/server'

// ─── Mock Data ─────────────────────────────────────────────

const mockData = {
  todaySummary: {
    totalFeed: 2850,
    totalCost: 8550,
    avgFCR: 1.61,
    waterRatio: 2.1,
    batchCount: 6,
    avgTemp: 28.5,
    avgHumidity: 72,
  },
  batchPlans: [
    {
      batchId: 'B2025-008',
      house: 'A1栋',
      breed: 'AA肉鸡',
      ageDays: 35,
      quantity: 12500,
      currentWeight: 2.1,
      targetWeight: 2.5,
      feedPerBird: 125,
      formula: '育肥期',
      feedings: 4,
      waterRatio: 2.2,
      protein: '20%',
      energy: '3200kcal/kg',
      dailyFeed: 1562.5,
      healthStatus: '健康',
      stageProgress: 88,
    },
    {
      batchId: 'B2025-009',
      house: 'A2栋',
      breed: 'AA肉鸡',
      ageDays: 28,
      quantity: 12000,
      currentWeight: 1.65,
      targetWeight: 2.5,
      feedPerBird: 108,
      formula: '生长期',
      feedings: 4,
      waterRatio: 2.0,
      protein: '21%',
      energy: '3100kcal/kg',
      dailyFeed: 1296,
      healthStatus: '健康',
      stageProgress: 70,
    },
    {
      batchId: 'B2025-010',
      house: 'B1栋',
      breed: '黄羽肉鸡',
      ageDays: 21,
      quantity: 8000,
      currentWeight: 0.85,
      targetWeight: 1.8,
      feedPerBird: 72,
      formula: '生长期',
      feedings: 3,
      waterRatio: 2.3,
      protein: '21%',
      energy: '3100kcal/kg',
      dailyFeed: 576,
      healthStatus: '良好',
      stageProgress: 52,
    },
    {
      batchId: 'B2025-011',
      house: 'B2栋',
      breed: 'AA肉鸡',
      ageDays: 14,
      quantity: 15000,
      currentWeight: 0.42,
      targetWeight: 2.5,
      feedPerBird: 52,
      formula: '育雏期',
      feedings: 4,
      waterRatio: 2.5,
      protein: '23%',
      energy: '3000kcal/kg',
      dailyFeed: 780,
      healthStatus: '健康',
      stageProgress: 35,
    },
    {
      batchId: 'B2025-012',
      house: 'A1栋',
      breed: '817肉杂',
      ageDays: 42,
      quantity: 10000,
      currentWeight: 2.45,
      targetWeight: 2.5,
      feedPerBird: 118,
      formula: '育肥期',
      feedings: 4,
      waterRatio: 2.1,
      protein: '19%',
      energy: '3300kcal/kg',
      dailyFeed: 1180,
      healthStatus: '待出栏',
      stageProgress: 98,
    },
    {
      batchId: 'B2025-013',
      house: 'A2栋',
      breed: '黄羽肉鸡',
      ageDays: 7,
      quantity: 9500,
      currentWeight: 0.15,
      targetWeight: 1.8,
      feedPerBird: 22,
      formula: '育雏期',
      feedings: 6,
      waterRatio: 2.8,
      protein: '23%',
      energy: '3000kcal/kg',
      dailyFeed: 209,
      healthStatus: '健康',
      stageProgress: 17,
    },
  ],
  feedFormulas: [
    {
      name: '育雏期 (0-14天)',
      stage: 'starter',
      protein: 23,
      energy: 3000,
      calcium: 1.0,
      phosphorus: 0.45,
      lysine: 1.2,
      methionine: 0.5,
      fat: 5.0,
      fiber: 3.0,
      suitableAge: '0-14天',
      pricePerKg: 3.8,
    },
    {
      name: '生长期 (15-28天)',
      stage: 'grower',
      protein: 21,
      energy: 3100,
      calcium: 0.9,
      phosphorus: 0.42,
      lysine: 1.1,
      methionine: 0.45,
      fat: 5.5,
      fiber: 3.5,
      suitableAge: '15-28天',
      pricePerKg: 3.5,
    },
    {
      name: '育肥期 (29-42天)',
      stage: 'finisher',
      protein: 19,
      energy: 3300,
      calcium: 0.85,
      phosphorus: 0.4,
      lysine: 1.0,
      methionine: 0.4,
      fat: 6.0,
      fiber: 4.0,
      suitableAge: '29-42天',
      pricePerKg: 3.2,
    },
    {
      name: '出栏前期 (43天+)',
      stage: 'pre-market',
      protein: 17,
      energy: 3200,
      calcium: 0.8,
      phosphorus: 0.38,
      lysine: 0.9,
      methionine: 0.38,
      fat: 5.0,
      fiber: 4.5,
      suitableAge: '43天以上',
      pricePerKg: 3.0,
    },
  ],
  feedingSchedule: [
    { time: '06:00', type: '早餐', percent: 25, feed: 712.5, notes: '添加维生素, 促进食欲', icon: 'sunrise' },
    { time: '10:00', type: '上午加餐', percent: 25, feed: 712.5, notes: '检查采食情况', icon: 'sun' },
    { time: '14:00', type: '午餐', percent: 30, feed: 855.0, notes: '充足饮水, 避免高温', icon: 'cloud-sun' },
    { time: '18:00', type: '晚餐', percent: 20, feed: 570.0, notes: '清理料槽, 记录余料', icon: 'sunset' },
  ],
  fcrTrend: [
    { week: '第1周', fcr: 1.15, costPerKg: 4.2, weightGain: 0.12, feedIntake: 0.14 },
    { week: '第2周', fcr: 1.28, costPerKg: 4.5, weightGain: 0.28, feedIntake: 0.36 },
    { week: '第3周', fcr: 1.42, costPerKg: 4.8, weightGain: 0.38, feedIntake: 0.54 },
    { week: '第4周', fcr: 1.52, costPerKg: 5.1, weightGain: 0.42, feedIntake: 0.64 },
    { week: '第5周', fcr: 1.58, costPerKg: 5.3, weightGain: 0.40, feedIntake: 0.63 },
    { week: '第6周', fcr: 1.61, costPerKg: 5.5, weightGain: 0.35, feedIntake: 0.56 },
  ],
  envAdjustments: {
    currentTemp: 28.5,
    currentHumidity: 72,
    tempEffect: '高温天气建议减少3-5%饲料量，增加饮水量和维生素补充',
    humidityEffect: '湿度偏高注意防霉，建议加强通风和料槽清洁频次',
    overall: '建议微调饲喂方案：增加早晚饲喂比例，减少午间高温时段饲喂',
    suggestions: [
      '将30%的饲料转移到清晨06:00前投喂',
      '饮水温度控制在20-25°C为宜',
      '饲料中添加维生素C 200mg/kg缓解热应激',
      '湿料禁止放置超过2小时，防止霉变',
    ],
    riskLevel: 'medium' as const,
  },
}

// ─── GET Handler ────────────────────────────────────────────

export async function GET() {
  try {
    return NextResponse.json(mockData)
  } catch (error) {
    console.error('[Smart Feeding API] Error:', error)
    const mockData = {
      todaySummary: { totalFeed: 2850, totalCost: 8550, avgFCR: 1.61, waterRatio: 2.1, batchCount: 6, avgTemp: 28.5, avgHumidity: 72 },
      batchPlans: [
        { batchId: 'B2025-008', house: 'A1栋', breed: 'AA肉鸡', ageDays: 35, quantity: 12500, currentWeight: 2.1, targetWeight: 2.5, feedPerBird: 125, formula: '育肥期', feedings: 4, waterRatio: 2.2, protein: '20%', energy: '3200kcal/kg', dailyFeed: 1562.5, healthStatus: '健康', stageProgress: 88 },
        { batchId: 'B2025-009', house: 'A2栋', breed: 'AA肉鸡', ageDays: 28, quantity: 12000, currentWeight: 1.65, targetWeight: 2.5, feedPerBird: 108, formula: '生长期', feedings: 4, waterRatio: 2.0, protein: '21%', energy: '3100kcal/kg', dailyFeed: 1296, healthStatus: '健康', stageProgress: 70 },
      ],
      feedFormulas: [
        { name: '育雏期 (0-14天)', stage: 'starter', protein: 23, energy: 3000, calcium: 1.0, phosphorus: 0.45, lysine: 1.2, methionine: 0.5, fat: 5.0, fiber: 3.0, suitableAge: '0-14天', pricePerKg: 3.8 },
        { name: '生长期 (15-28天)', stage: 'grower', protein: 21, energy: 3100, calcium: 0.9, phosphorus: 0.42, lysine: 1.1, methionine: 0.45, fat: 5.5, fiber: 3.5, suitableAge: '15-28天', pricePerKg: 3.5 },
        { name: '育肥期 (29-42天)', stage: 'finisher', protein: 19, energy: 3300, calcium: 0.85, phosphorus: 0.4, lysine: 1.0, methionine: 0.4, fat: 6.0, fiber: 4.0, suitableAge: '29-42天', pricePerKg: 3.2 },
      ],
      feedingSchedule: [
        { time: '06:00', type: '早餐', percent: 25, feed: 712.5, notes: '添加维生素', icon: 'sunrise' },
        { time: '10:00', type: '上午加餐', percent: 25, feed: 712.5, notes: '检查采食情况', icon: 'sun' },
        { time: '14:00', type: '午餐', percent: 30, feed: 855.0, notes: '充足饮水', icon: 'cloud-sun' },
        { time: '18:00', type: '晚餐', percent: 20, feed: 570.0, notes: '清理料槽', icon: 'sunset' },
      ],
      fcrTrend: [
        { week: '第1周', fcr: 1.15, costPerKg: 4.2, weightGain: 0.12, feedIntake: 0.14 },
        { week: '第2周', fcr: 1.28, costPerKg: 4.5, weightGain: 0.28, feedIntake: 0.36 },
        { week: '第3周', fcr: 1.42, costPerKg: 4.8, weightGain: 0.38, feedIntake: 0.54 },
        { week: '第4周', fcr: 1.52, costPerKg: 5.1, weightGain: 0.42, feedIntake: 0.64 },
        { week: '第5周', fcr: 1.58, costPerKg: 5.3, weightGain: 0.40, feedIntake: 0.63 },
        { week: '第6周', fcr: 1.61, costPerKg: 5.5, weightGain: 0.35, feedIntake: 0.56 },
      ],
      envAdjustments: { currentTemp: 28.5, currentHumidity: 72, tempEffect: '高温天气建议减少3-5%饲料量', humidityEffect: '湿度偏高注意防霉', overall: '建议微调饲喂方案', suggestions: ['将30%的饲料转移到清晨06:00前投喂', '饮水温度控制在20-25°C为宜'], riskLevel: 'medium' as const },
    }
    return NextResponse.json(mockData)
  }
}
