import { NextResponse } from 'next/server'

export async function GET() {
  const data = {
    stats: {
      totalDiseases: 16,
      activeAlerts: 2,
      vaccinationRate: 94.5,
      monthlyCases: 3,
    },

    categories: [
      {
        name: '病毒性疾病',
        type: 'viral',
        icon: 'Bug',
        color: '#ef4444',
        description: '由病毒引起的传染病，传播速度快，危害严重',
        diseases: [
          {
            name: '新城疫',
            severity: 'high',
            symptoms: ['呼吸困难、气喘', '神经症状（扭颈、观星）', '排绿色稀便', '产蛋率骤降', '腺胃乳头出血'],
            prevention: ['按时疫苗接种（Lasota、Clone30）', '严格隔离消毒制度', '控制人员车辆进出', '加强饲养管理提高免疫力'],
            treatment: ['紧急接种Clone30疫苗', '使用抗病毒药物辅助治疗', '添加多维电解质', '抗生素防止继发感染', '淘汰重症鸡只'],
            season: '冬春',
            ageRange: '所有日龄',
          },
          {
            name: '禽流感',
            severity: 'high',
            symptoms: ['突发高热（41-42℃）', '头部水肿、肉髯发紫', '呼吸困难、张口呼吸', '下痢、排黄绿色粪便', '脚鳞出血'],
            prevention: ['定期接种禽流感灭活疫苗', '严格执行生物安全措施', '禁止与野生鸟类接触', '加强环境消毒（含氯消毒剂）'],
            treatment: ['立即上报疫情', '配合政府扑杀措施', '全场紧急消毒', '封场隔离', '对周边区域进行监测'],
            season: '冬春',
            ageRange: '所有日龄',
          },
          {
            name: '传染性支气管炎',
            severity: 'medium',
            symptoms: ['咳嗽、喷嚏、气管啰音', '鼻窦肿胀、流鼻涕', '产蛋下降、畸形蛋增多', '肾型：尿酸盐沉积', '输卵管发育不良'],
            prevention: ['7日龄首免H120疫苗', '35日龄二免H52疫苗', '开产前接种灭活疫苗', '保持舍内温度稳定', '减少应激因素'],
            treatment: ['使用抗病毒药物（利巴韦林）', '添加止咳平喘药物', '补充多维增强抵抗力', '使用抗生素防继发感染', '保温并改善通风'],
            season: '秋冬',
            ageRange: '1-6周龄最易感',
          },
          {
            name: '传染性法氏囊病',
            severity: 'high',
            symptoms: ['精神萎靡、羽毛蓬松', '排白色水样稀便', '法氏囊肿大出血', '脱水、消瘦', '免疫抑制导致继发感染'],
            prevention: ['14-18日龄首免法氏囊疫苗', '28-32日龄二免', '做好环境消毒（碘制剂）', '控制舍内湿度', '母源抗体监测'],
            treatment: ['注射高免卵黄抗体', '使用肾肿解毒药', '补充电解多维', '添加抗生素防继发感染', '提高舍温2-3℃'],
            season: '春夏',
            ageRange: '3-6周龄',
          },
        ],
      },
      {
        name: '细菌性疾病',
        type: 'bacterial',
        icon: 'Microscope',
        color: '#f59e0b',
        description: '由细菌感染引起的疾病，常与饲养环境密切相关',
        diseases: [
          {
            name: '大肠杆菌病',
            severity: 'medium',
            symptoms: ['心包炎、肝周炎', '气囊浑浊增厚', '卵黄性腹膜炎', '排黄白色稀便', '败血症、突然死亡'],
            prevention: ['加强环境卫生管理', '控制饲养密度', '减少氨气等有害气体', '种蛋严格消毒', '定期预防性投药'],
            treatment: ['药敏试验选择敏感药物', '常用恩诺沙星、氟苯尼考', '交替用药防止耐药', '配合中药制剂', '淘汰病重鸡只'],
            season: '全年',
            ageRange: '各日龄均可发生',
          },
          {
            name: '沙门氏菌病',
            severity: 'medium',
            symptoms: ['雏鸡排白色糊状粪便', '肛门周围羽毛粘结', '精神沉郁、食欲废绝', '肺型：呼吸困难', '关节肿大、跛行'],
            prevention: ['种鸡群净化', '种蛋熏蒸消毒', '雏鸡入舍前消毒', '防止饲料水源污染', '添加微生态制剂'],
            treatment: ['氟苯尼考拌料', '恩诺沙星饮水', '硫酸粘菌素拌料', '补充电解多维', '严重鸡群及时淘汰'],
            season: '春夏',
            ageRange: '雏鸡最易感（1-3周龄）',
          },
          {
            name: '鸡白痢',
            severity: 'medium',
            symptoms: ['排白色石灰样粪便', '肛门被粪便堵塞', '翅膀下垂、闭眼嗜睡', '扎堆、怕冷', '生长发育迟缓'],
            prevention: ['种鸡白痢净化检测', '种蛋孵化消毒', '雏鸡开口添加抗菌药', '育雏温度适宜', '坚持全进全出制度'],
            treatment: ['恩诺沙星饮水5天', '氟苯尼考拌料', '复方新诺明拌料', '电解多维饮水', '改善育雏环境'],
            season: '冬春',
            ageRange: '1-3周龄雏鸡',
          },
          {
            name: '禽霍乱',
            severity: 'high',
            symptoms: ['突然死亡（急性型）', '鸡冠肉髯发紫肿胀', '剧烈腹泻、粪便带血', '体温升至43-44℃', '肝脏表面有灰白色坏死点'],
            prevention: ['定期接种禽霍乱灭活疫苗', '严格消毒鸡舍及用具', '减少应激因素', '防止水源饲料污染', '病死鸡无害化处理'],
            treatment: ['青霉素+链霉素肌肉注射', '恩诺沙星饮水', '磺胺类药物拌料', '全场紧急消毒', '隔离病鸡群'],
            season: '夏秋',
            ageRange: '成年鸡多发',
          },
        ],
      },
      {
        name: '寄生虫性疾病',
        type: 'parasitic',
        icon: 'Bug',
        color: '#22c55e',
        description: '由寄生虫引起的疾病，影响生长性能和饲料转化率',
        diseases: [
          {
            name: '球虫病',
            severity: 'high',
            symptoms: ['血便、番茄样粪便', '精神萎靡、食欲下降', '鸡冠苍白贫血', '生长迟缓、料肉比升高', '盲肠肿胀出血'],
            prevention: ['雏鸡使用抗球虫药物预防', '保持垫料干燥清洁', '控制饲养密度', '定期轮换用药', '使用球虫疫苗免疫'],
            treatment: ['地克珠利饮水', '磺胺氯丙嗪钠饮水', '托曲珠利饮水', '补充维生素K止血', '电解多维恢复体力'],
            season: '春夏雨季',
            ageRange: '15-50日龄最易感',
          },
          {
            name: '蛔虫病',
            severity: 'low',
            symptoms: ['生长缓慢、消瘦', '产蛋率下降', '腹泻、偶尔带虫', '羽毛粗乱无光泽', '严重感染时肠梗阻'],
            prevention: ['定期驱虫（每2个月）', '及时清理鸡粪', '保持运动场干燥', '饲料中添加驱虫药', '做好饮水卫生'],
            treatment: ['伊维菌素拌料', '芬苯达唑拌料', '左旋咪唑饮水', '驱虫后补充营养', '粪便堆积发酵杀虫卵'],
            season: '全年',
            ageRange: '2月龄以上鸡群',
          },
          {
            name: '住白细胞原虫病',
            severity: 'medium',
            symptoms: ['鸡冠苍白、贫血', '排绿色稀便', '咳血、呼吸困难', '运动失调、共济失调', '肌肉及内脏出血'],
            prevention: ['消灭库蠓等传播媒介', '鸡舍安装防虫网', '使用杀虫剂喷洒环境', '流行季节预防性投药', '减少户外活动时间'],
            treatment: ['磺胺间甲氧嘧啶饮水', '乙胺嘧啶拌料', '复方新诺明拌料', '添加维生素K', '补充铁剂改善贫血'],
            season: '夏秋',
            ageRange: '1-3月龄青年鸡',
          },
          {
            name: '组织滴虫病',
            severity: 'low',
            symptoms: ['排硫磺色粪便', '头部发黑（黑头病）', '盲肠肿大、干酪样渗出', '肝脏出现同心圆坏死灶', '精神沉郁、食欲减退'],
            prevention: ['定期驱除异刺线虫', '避免鸡与火鸡混养', '保持环境卫生', '及时清除粪便', '做好饮水消毒'],
            treatment: ['甲硝唑饮水', '卡巴胂拌料', '地美硝唑预混剂', '补充多维恢复体质', '改善环境卫生'],
            season: '春夏',
            ageRange: '4-16周龄',
          },
        ],
      },
      {
        name: '营养代谢性疾病',
        type: 'metabolic',
        icon: 'Pill',
        color: '#a855f7',
        description: '由营养失衡或代谢障碍引起的疾病，多与饲料管理有关',
        diseases: [
          {
            name: '痛风',
            severity: 'medium',
            symptoms: ['关节肿大、行动困难', '内脏表面尿酸盐沉积', '排白色稀便（含尿酸盐）', '食欲下降、精神萎靡', '肾脏肿大苍白'],
            prevention: ['合理搭配饲料蛋白含量', '保证充足饮水', '控制钙磷比例适当', '避免长期使用磺胺类药物', '添加维生素A促进尿酸排出'],
            treatment: ['降低饲料蛋白质水平', '补充充足清洁饮水', '添加碳酸氢钠碱化尿液', '增加维生素A、D的供给', '使用肾肿解毒药'],
            season: '全年',
            ageRange: '肉鸡3-6周龄、蛋鸡产蛋期',
          },
          {
            name: '脂肪肝综合征',
            severity: 'low',
            symptoms: ['鸡冠苍白或发黄', '产蛋率突然下降', '过度肥胖、体重超标', '肝脏肿大呈黄色', '突然死亡（肝破裂）'],
            prevention: ['合理控制能量饲料', '添加氯化胆碱和蛋氨酸', '保证适当运动空间', '避免饲料突变应激', '控制日粮能量蛋白比'],
            treatment: ['降低饲料能量水平', '添加氯化胆碱（每吨1000g）', '补充维生素B12和叶酸', '添加维生素E和硒', '逐步调整饲料配方'],
            season: '夏季高温期',
            ageRange: '产蛋高峰期母鸡',
          },
          {
            name: '维生素缺乏症',
            severity: 'low',
            symptoms: ['VA缺乏：夜盲、上皮角化', 'VD缺乏：佝偻病、软壳蛋', 'VE缺乏：脑软化、渗出性素质', 'VB缺乏：脚趾蜷曲、生长停滞', 'VK缺乏：出血不止'],
            prevention: ['使用优质维生素预混料', '注意维生素保存（避光防潮）', '定期检测饲料维生素含量', '应激期间增加维生素添加量', '饲料加工温度不宜过高'],
            treatment: ['确诊缺乏种类后针对性补充', '紧急注射对应维生素制剂', '饮水添加复合维生素', '调整饲料配方', '使用抗氧化剂保护维生素'],
            season: '全年',
            ageRange: '快速生长期和产蛋高峰期',
          },
          {
            name: '矿物质代谢紊乱',
            severity: 'low',
            symptoms: ['钙磷缺乏：软骨症、产软壳蛋', '锌缺乏：羽毛异常、皮肤角化', '锰缺乏：滑腱症、跛行', '硒缺乏：渗出性素质', '铁缺乏：贫血'],
            prevention: ['使用优质矿物质预混料', '定期检测饲料矿物质含量', '注意矿物质间拮抗关系', '应激期适当增加添加量', '保证饮水清洁'],
            treatment: ['确诊后针对性补充矿物质', '调整饲料矿物质配比', '饮水添加电解多维', '严重个体注射补充', '持续监测恢复情况'],
            season: '全年',
            ageRange: '各日龄均可发生',
          },
        ],
      },
    ],

    seasonalRisk: [
      { month: '1月', risks: [
        { disease: '新城疫', level: 'high' },
        { disease: '禽流感', level: 'high' },
        { disease: '传染性支气管炎', level: 'medium' },
        { disease: '鸡白痢', level: 'medium' },
      ]},
      { month: '2月', risks: [
        { disease: '新城疫', level: 'high' },
        { disease: '禽流感', level: 'high' },
        { disease: '传染性支气管炎', level: 'high' },
        { disease: '鸡白痢', level: 'medium' },
      ]},
      { month: '3月', risks: [
        { disease: '新城疫', level: 'medium' },
        { disease: '传染性法氏囊病', level: 'medium' },
        { disease: '大肠杆菌病', level: 'medium' },
        { disease: '沙门氏菌病', level: 'low' },
      ]},
      { month: '4月', risks: [
        { disease: '传染性法氏囊病', level: 'high' },
        { disease: '球虫病', level: 'medium' },
        { disease: '大肠杆菌病', level: 'medium' },
        { disease: '沙门氏菌病', level: 'low' },
      ]},
      { month: '5月', risks: [
        { disease: '球虫病', level: 'high' },
        { disease: '传染性法氏囊病', level: 'medium' },
        { disease: '大肠杆菌病', level: 'medium' },
        { disease: '组织滴虫病', level: 'low' },
      ]},
      { month: '6月', risks: [
        { disease: '球虫病', level: 'high' },
        { disease: '脂肪肝综合征', level: 'medium' },
        { disease: '大肠杆菌病', level: 'medium' },
        { disease: '住白细胞原虫病', level: 'low' },
      ]},
      { month: '7月', risks: [
        { disease: '脂肪肝综合征', level: 'high' },
        { disease: '禽霍乱', level: 'high' },
        { disease: '住白细胞原虫病', level: 'medium' },
        { disease: '球虫病', level: 'medium' },
      ]},
      { month: '8月', risks: [
        { disease: '禽霍乱', level: 'high' },
        { disease: '住白细胞原虫病', level: 'high' },
        { disease: '脂肪肝综合征', level: 'medium' },
        { disease: '球虫病', level: 'medium' },
      ]},
      { month: '9月', risks: [
        { disease: '禽霍乱', level: 'medium' },
        { disease: '住白细胞原虫病', level: 'medium' },
        { disease: '大肠杆菌病', level: 'medium' },
        { disease: '组织滴虫病', level: 'low' },
      ]},
      { month: '10月', risks: [
        { disease: '传染性支气管炎', level: 'medium' },
        { disease: '大肠杆菌病', level: 'medium' },
        { disease: '禽霍乱', level: 'low' },
        { disease: '痛风', level: 'low' },
      ]},
      { month: '11月', risks: [
        { disease: '新城疫', level: 'high' },
        { disease: '传染性支气管炎', level: 'high' },
        { disease: '大肠杆菌病', level: 'medium' },
        { disease: '痛风', level: 'low' },
      ]},
      { month: '12月', risks: [
        { disease: '新城疫', level: 'high' },
        { disease: '禽流感', level: 'high' },
        { disease: '传染性支气管炎', level: 'high' },
        { disease: '鸡白痢', level: 'medium' },
      ]},
    ],

    vaccinationSchedule: [
      { age: '1日龄', vaccine: '马立克氏病疫苗', method: '皮下注射', description: '雏鸡出壳后24小时内接种', type: '必免' },
      { age: '7日龄', vaccine: '新城疫Lasota + 传染性支气管炎H120', method: '点眼/滴鼻', description: '首免，建立基础免疫', type: '必免' },
      { age: '14日龄', vaccine: '传染性法氏囊病活疫苗', method: '饮水免疫', description: '首免，预防法氏囊病', type: '必免' },
      { age: '21日龄', vaccine: '禽流感灭活疫苗（H5+H7）', method: '颈部皮下注射', description: '首免禽流感疫苗', type: '必免' },
      { age: '35日龄', vaccine: '新城疫Lasota + 传染性支气管炎H52', method: '点眼/饮水', description: '二免新城疫和传支', type: '必免' },
      { age: '60日龄', vaccine: '禽流感灭活疫苗（H5+H7）', method: '肌肉注射', description: '二免禽流感，加强免疫', type: '必免' },
      { age: '90日龄', vaccine: '新城疫I系苗', method: '肌肉注射', description: '加强免疫新城疫', type: '必免' },
      { age: '120日龄', vaccine: '新城疫-传支-减蛋综合征三联灭活苗', method: '肌肉注射', description: '开产前免疫，保护产蛋期', type: '必免' },
    ],

    emergencyProtocol: [
      {
        step: 1,
        title: '立即隔离',
        description: '将疑似病鸡立即转移至隔离舍，与健康鸡群完全分开。关闭发病鸡舍通道，禁止无关人员进入。',
        icon: 'Shield',
        timeLimit: '30分钟内',
      },
      {
        step: 2,
        title: '现场封锁',
        description: '对发病鸡舍及周边区域实施封锁管理。设立警示标识，所有进出人员和物品必须严格消毒。',
        icon: 'AlertTriangle',
        timeLimit: '1小时内',
      },
      {
        step: 3,
        title: '采样送检',
        description: '采集病鸡的血液、粪便、组织等样本，送往兽医实验室进行病原学检测和药敏试验。',
        icon: 'Microscope',
        timeLimit: '2小时内',
      },
      {
        step: 4,
        title: '紧急消毒',
        description: '使用含氯消毒剂或过氧乙酸对鸡舍、用具、环境进行全面消毒。每日消毒2次，连续7天。',
        icon: 'Syringe',
        timeLimit: '4小时内',
      },
      {
        step: 5,
        title: '跟踪报告',
        description: '建立疫情档案，每日记录发病数、死亡数、治疗情况。重大疫情按规定向当地兽医主管部门报告。',
        icon: 'FileWarning',
        timeLimit: '持续跟踪',
      },
    ],

    healthScore: {
      immunity: 94,
      hygiene: 88,
      biosecurity: 82,
      nutrition: 91,
      monitoring: 85,
    },
  }

  return NextResponse.json(data)
}
